services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=passguard
      - POSTGRES_PASSWORD=passguard
      - POSTGRES_DB=passguarddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: